/**
 * Canonical identity of the site, in one place.
 *
 * The host is `www` because that is what actually serves: the apex 301s to it.
 * Canonicals, Open Graph URLs, the sitemap and robots.txt all have to agree
 * with that, or every canonical points at a redirect.
 */
export const SITE_URL = 'https://www.ganhammar.se';
export const SITE_NAME = 'Ganhammar';
export const SITE_DESCRIPTION = "Notes on serverless, .NET, and whatever I've just taken apart.";
export const AUTHOR = 'Anton Ganhammar';
export const AUTHOR_URL = `${SITE_URL}/about`;

/** 1200x630 social card, regenerated by scripts/og-card.mjs. */
export const OG_IMAGE = `${SITE_URL}/og.png`;
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;
