service: Game
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

plugins:
  - serverless-s3-sync
  - serverless-offline
  - serverless-s3-local

custom:
  s3Sync:
    endpoint: http://localhost:3001
    buckets:
      - bucketName: 'ganhammar.se-${sls:stage}'
        localDir: src
  serverless-offline:
    lambdaPort: 3003
