service: Game
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

plugins:
  - serverless-s3-sync
  - serverless-offline
  - serverless-s3-local

custom:
  gameBucketName: 'ganhammar.se-${sls:stage}'
  s3Sync:
    endpoint: http://localhost:3001
    buckets:
      - bucketName: ${self:custom.gameBucketName}
        localDir: src
  serverless-offline:
    lambdaPort: 3003

resources:
  Resources:
    GameBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gameBucketName}
    GameDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: 'index.html'
          HttpVersion: http2
          Origins:
            - Id: S3Origin
              DomainName: '${self:custom.gameBucketName}.s3.${self:provider.region}.amazonaws.com'
              S3OriginConfig:
                OriginAccessIdentity: origin-access-identity/cloudfront/EAT3VRKE0H9H1
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Aliases:
            - ganhammar.se
            - www.ganhammar.se
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:519157272275:certificate/af61fc26-27ea-4cd5-83b1-09bdae39ab41
            SslSupportMethod: sni-only
