service: Game
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

plugins:
  - serverless-s3-sync
  - serverless-offline
  - serverless-s3-local

custom:
  gameBucketName: 'ganhammar.se-${sls:stage}'
  s3Sync:
    endpoint: http://localhost:3001
    buckets:
      - bucketName: ${self:custom.gameBucketName}
        localDir: src
  serverless-offline:
    lambdaPort: 3003

resources:
  Resources:
    GanhammarGame:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gameBucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
