name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ID }} --secret ${{ secrets.AWS_SECRET }}
      - name: 'Backend: Install Dependencies'
        working-directory: ./Backend/Highscore
        run: npm ci
      - name: 'Backend: Deploy'
        working-directory: ./Backend/Highscore
        run: sls deploy -s prod
      - name: 'Frontend: Deploy'
        working-directory: ./Frontend/Game
        run: sls deploy -s prod