name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install, Build & Test
        run: |
          npm ci
          npm test
        env:
          CI: true
  publish:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install & Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - uses: tibor19/static-website-deploy@v1
        with:
          name: Publish
          enabled-static-website: 'true'
          folder: 'build'
          connection-string: ${{ secrets.CONNECTION_STRING }}