name: CI-CD

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          role-session-name: OIDCSession

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build SvelteKit
        run: npm run build

      - name: End-to-end test
        run: npm run test:e2e
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Deploy CDK
        if: github.ref == 'refs/heads/main'
        run: npm run deploy
        env:
          CI: true
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Smoke test
        if: github.ref == 'refs/heads/main'
        run: npm run test:smoke
